channels:
- conda-forge
- bioconda
- defaults
dependencies:
- bioconductor-dada2=1.6.0=r3.4.1_0
- qiime=1.9.1=np112py27_1
- scikit-bio=0.2.3=np112py27_0
- python=2.7.14=5
- r-argparser=0.4=r3.4.1_0
- r-base=3.4.1=3
- rpy2=2.8.5=py27r3.4.1_0
- pip:
  - git+https://github.com/shafferm/dada2_qiime1.git
